### ISSUE TITLE
[RPG] when trying to do [p]items an error occurs

### ISSUE THREAD

**Issue by kennnyshiwa** [baiumbg/useless-cogs#13]
When attempting to do ``[p]items`` its expected to respond with the duel items list, but it errors out with 

```
Exception in command 'items'
Traceback (most recent call last):
  File "c:\python37\lib\site-packages\discord\ext\commands\core.py", line 79, in wrapped
    ret = await coro(*args, **kwargs)
  File "C:\Users\Kenneth\AppData\Local\Red-DiscordBot\Red-DiscordBot\cogs\CogManager\cogs\rpg\rpg.py", line 877, in _items
    await ctx.invoke(self._duelitems_list, category)
AttributeError: 'RPG' object has no attribute '_duelitems_list'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "c:\python37\lib\site-packages\discord\ext\commands\bot.py", line 863, in invoke
    await ctx.command.invoke(ctx)
  File "c:\python37\lib\site-packages\redbot\core\commands\commands.py", line 582, in invoke
    await super().invoke(ctx)
  File "c:\python37\lib\site-packages\discord\ext\commands\core.py", line 1163, in invoke
    await super().invoke(ctx)
  File "c:\python37\lib\site-packages\discord\ext\commands\core.py", line 728, in invoke
    await injected(*ctx.args, **ctx.kwargs)
  File "c:\python37\lib\site-packages\discord\ext\commands\core.py", line 88, in wrapped
    raise CommandInvokeError(exc) from exc
discord.ext.commands.errors.CommandInvokeError: Command raised an exception: AttributeError: 'RPG' object has no attribute '_duelitems_list'```

**Comment by baiumbg** [comment]
Whoops, my bad. Fix committed to `master`. Do `[p]cog update` to pull the fix.
