### ISSUE TITLE
[TTS] Couldn't find ffprobe or avprobe

### ISSUE THREAD

**Issue by pabloleban** [baiumbg/useless-cogs#15]
Im getting this whenever I run !tts command:

`C:\Users\Admin\Desktop\obesin\cogs\Downloader\lib\pydub\utils.py:193: RuntimeWarning: Couldn't find ffprobe or avprobe - defaulting to ffprobe, but may not work
  warn("Couldn't find ffprobe or avprobe - defaulting to ffprobe, but may not work", RuntimeWarning)
[2020-01-07 12:41:50] [ERROR] red: Exception in command 'tts'
Traceback (most recent call last):
  File "C:\Users\Admin\AppData\Roaming\Python\Python38\site-packages\discord\ext\commands\core.py", line 79, in wrapped
    ret = await coro(*args, **kwargs)
  File "C:\Users\Admin\Desktop\obesin\cogs\CogManager\cogs\sfx\sfx.py", line 65, in tts
    audio_data = pydub.AudioSegment.from_mp3(audio_file)
  File "C:\Users\Admin\Desktop\obesin\cogs\Downloader\lib\pydub\audio_segment.py", line 716, in from_mp3
    return cls.from_file(file, 'mp3', parameters=parameters)
  File "C:\Users\Admin\Desktop\obesin\cogs\Downloader\lib\pydub\audio_segment.py", line 665, in from_file
    info = mediainfo_json(orig_file)
  File "C:\Users\Admin\Desktop\obesin\cogs\Downloader\lib\pydub\utils.py", line 263, in mediainfo_json
    res = Popen(command, stdin=stdin_parameter, stdout=PIPE, stderr=PIPE)
  File "c:\users\admin\appdata\local\programs\python\python38\lib\subprocess.py", line 854, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "c:\users\admin\appdata\local\programs\python\python38\lib\subprocess.py", line 1307, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] El sistema no puede encontrar el archivo especificado`

Have I installed the cog requirements incorrectly?

**Comment by baiumbg** [comment]
TTS requires ffmpeg to be installed on the machine that is running Red - I should probably add that to the README 🤔 

Try again after installing it.

**Comment by pabloleban** [comment]
I've installed FFmpeg, added to the path and now it's working fine. Thanks.
