### ISSUE TITLE
Issue adding sound effect files

### ISSUE THREAD

**Issue by muppetdakoda** [baiumbg/useless-cogs#16]
Hey, I've been trying to fix this issue myself but have had no luck. Adding sound effects via Discord doesn't seem to be working. 

![image](https://user-images.githubusercontent.com/42357815/72194844-51cc9980-3407-11ea-9757-60d9d7f73327.png)

```[2020-01-11 00:13:48] [ERROR] red: Exception in command 'addsfx'
Traceback (most recent call last):
  File "c:\users\joshua\documents\audrey\redenv\lib\site-packages\discord\ext\commands\core.py", line 79, in wrapped
    ret = await coro(*args, **kwargs)
  File "C:\Users\Joshua\AppData\Local\Red-DiscordBot\Red-DiscordBot\data\Audrey\cogs\CogManager\cogs\sfx\sfx.py", line 214, in addsfx
    audio_data = pydub.AudioSegment.from_file(filepath, format=file_extension[1:])
  File "C:\Users\Joshua\AppData\Local\Red-DiscordBot\Red-DiscordBot\data\Audrey\cogs\Downloader\lib\pydub\audio_segment.py", line 665, in from_file
    info = mediainfo_json(orig_file)
  File "C:\Users\Joshua\AppData\Local\Red-DiscordBot\Red-DiscordBot\data\Audrey\cogs\Downloader\lib\pydub\utils.py", line 263, in mediainfo_json
    res = Popen(command, stdin=stdin_parameter, stdout=PIPE, stderr=PIPE)
  File "C:\Python38\lib\subprocess.py", line 854, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Python38\lib\subprocess.py", line 1307, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] The system cannot find the file specified
```

And I can't just put them all into the correct folder of the guild ID, it doesn't detect them. It does however, when I do `;addsfx` put it into that folder. It just can't play it afterwards or see it using `;allsfx`.

**Comment by baiumbg** [comment]
I suspect this is the same as #15. Install FFmpeg, add it to your path and see if that fixes it.

**Comment by muppetdakoda** [comment]
Thanks that fixed it :)
